'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Hls, { ErrorTypes } from 'hls.js';
import type { ErrorData } from 'hls.js';
import { Spinner } from '../Spinner/Spinner';
import styles from './Player.module.css';

export interface PlayerProps { urls: string[]; title: string; initialVolume?: number; initialLevel?: number; initialDataSaver?: boolean; onVolumeChange?: (volume: number) => void; onLevelChange?: (level: number) => void; onDataSaverChange?: (enabled: boolean) => void; }
interface QualityLevel { index: number; height: number; bitrate?: number; }
interface PlaybackStats { startupMs: number | null; rebufferCount: number; bufferAhead: number; bitrate: number | null; latency: number | null; }
const MAX_RETRIES = 2;
const MAX_NETWORK_RETRIES = 3;
const DATA_SAVER_MAX_HEIGHT = 480;
const STARTUP_DEADLINE_MS = 30_000;
function exponentialDelay(attempt: number): number { return Math.min(1000 * 2 ** attempt, 8000); }
function formatDuration(ms: number | null): string { return ms === null ? '…' : `${(ms / 1000).toFixed(1)} s`; }
function formatBuffer(seconds: number): string { return `${Math.max(0, seconds).toFixed(1)} s`; }
function networkProfile(): { estimate: number; capHeight: number | null; buffer: number } { const connection = (navigator as Navigator & { connection?: { effectiveType?: string; downlink?: number; saveData?: boolean } }).connection; const type = connection?.effectiveType; const downlink = connection?.downlink ?? 0; if (connection?.saveData || type === 'slow-2g' || type === '2g' || downlink > 0 && downlink < 1) return { estimate: 350_000, capHeight: 360, buffer: 8 }; if (type === '3g' || downlink > 0 && downlink < 3) return { estimate: 750_000, capHeight: 720, buffer: 12 }; return { estimate: 1_200_000, capHeight: null, buffer: 16 }; }

export function Player({ urls, title, initialVolume, initialLevel, initialDataSaver, onVolumeChange, onLevelChange, onDataSaverChange }: PlayerProps) {
  const videoRef = useRef<HTMLVideoElement>(null); const hlsRef = useRef<Hls | null>(null); const retryRef = useRef<(() => void) | null>(null); const startupAtRef = useRef(0); const rebufferCountRef = useRef(0);
  const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading'); const [buffering, setBuffering] = useState(false); const [levels, setLevels] = useState<QualityLevel[]>([]); const [activeLevel, setActiveLevel] = useState(-1); const [selectedLevel, setSelectedLevel] = useState(initialLevel ?? -1); const [dataSaver, setDataSaver] = useState(initialDataSaver ?? false); const [autoplayBlocked, setAutoplayBlocked] = useState(false); const [stats, setStats] = useState<PlaybackStats>({ startupMs: null, rebufferCount: 0, bufferAhead: 0, bitrate: null, latency: null }); const [retrying, setRetrying] = useState(false); const urlsKey = useMemo(() => urls.join('\n'), [urls]);

  useEffect(() => {
    const video = videoRef.current; if (!video || urls.length === 0) return; const el = video; let cancelled = false; let urlIndex = 0; let retries = 0; let networkRetries = 0; let started = false; let deadlineTimer: ReturnType<typeof setTimeout> | null = null; let retryTimer: ReturnType<typeof setTimeout> | null = null;
    startupAtRef.current = performance.now(); rebufferCountRef.current = 0; setStatus('loading'); setBuffering(false); setLevels([]); setActiveLevel(-1); setAutoplayBlocked(false); setRetrying(false); setStats({ startupMs: null, rebufferCount: 0, bufferAhead: 0, bitrate: null, latency: null });
    const clearTimers = (): void => { if (deadlineTimer) clearTimeout(deadlineTimer); if (retryTimer) clearTimeout(retryTimer); deadlineTimer = retryTimer = null; };
    const destroy = (): void => { const hls = hlsRef.current; if (hls) { hls.stopLoad(); hls.detachMedia(); hls.destroy(); } hlsRef.current = null; el.removeAttribute('src'); el.load(); };
    const bufferAhead = (): number => el.buffered.length === 0 ? 0 : Math.max(0, el.buffered.end(el.buffered.length - 1) - el.currentTime);
    const updateStats = (latency: number | null = null): void => setStats((current) => ({ ...current, bufferAhead: bufferAhead(), latency }));
    const markReady = (): void => { if (cancelled) return; started = true; retries = 0; networkRetries = 0; setStatus('ready'); setBuffering(false); setRetrying(false); setStats((current) => ({ ...current, startupMs: current.startupMs ?? performance.now() - startupAtRef.current, rebufferCount: rebufferCountRef.current, bufferAhead: bufferAhead() })); if (deadlineTimer) clearTimeout(deadlineTimer); };
    const advance = (): void => { if (cancelled) return; retries += 1; setRetrying(true); if (retries <= MAX_RETRIES) { retryTimer = setTimeout(loadCurrent, exponentialDelay(retries)); return; } if (urlIndex + 1 < urls.length) { urlIndex += 1; retries = 0; networkRetries = 0; loadCurrent(); return; } setStatus('error'); setRetrying(false); };
    function loadCurrent(): void {
      if (cancelled) return; clearTimers(); destroy(); setStatus('loading'); setRetrying(false); setLevels([]); setActiveLevel(-1); startupAtRef.current = performance.now(); if (!Hls.isSupported()) { el.src = urls[urlIndex]; el.load(); return; } started = false; deadlineTimer = setTimeout(() => { if (!cancelled && !started) advance(); }, STARTUP_DEADLINE_MS);
      const profile = networkProfile(); const hls = new Hls({ enableWorker: true, lowLatencyMode: false, startFragPrefetch: true, backBufferLength: 6, maxBufferLength: profile.buffer, maxMaxBufferLength: 24, maxBufferSize: 24 * 1000 * 1000, maxBufferHole: 0.5, liveSyncDurationCount: 5, liveMaxLatencyDurationCount: 12, startLevel: 0, abrEwmaDefaultEstimate: profile.estimate, abrEwmaFastVoD: 2, abrEwmaSlowVoD: 5, abrBandWidthFactor: 0.7, abrBandWidthUpFactor: 0.5, abrMaxWithRealBitrate: true, capLevelToPlayerSize: true, maxLoadingDelay: 2, maxFragLookUpTolerance: 0.3, manifestLoadingTimeOut: 15_000, manifestLoadingMaxRetry: 3, levelLoadingTimeOut: 15_000, levelLoadingMaxRetry: 3, fragLoadingTimeOut: 20_000, fragLoadingMaxRetry: 4, maxStarvationDelay: 4 });
      hlsRef.current = hls; retryRef.current = loadCurrent; hls.loadSource(urls[urlIndex]); hls.attachMedia(el);
      hls.on(Hls.Events.ERROR, (_event, data: ErrorData) => { if (cancelled || !data.fatal) return; if (data.type === ErrorTypes.MEDIA_ERROR) { if (el.buffered.length > 0 && el.currentTime + 0.5 < el.buffered.end(el.buffered.length - 1)) el.currentTime += 0.5; hls.recoverMediaError(); return; } if (data.type === ErrorTypes.NETWORK_ERROR) { const code = data.response?.code; const master = typeof data.url === 'string' && data.url.includes('master.m3u8'); if (code === 401 || code === 403 || (code === 404 && master)) { if (urlIndex + 1 < urls.length) { urlIndex += 1; retries = 0; networkRetries = 0; loadCurrent(); } else setStatus('error'); return; } if ([Hls.ErrorDetails.MANIFEST_LOAD_ERROR, Hls.ErrorDetails.MANIFEST_LOAD_TIMEOUT, Hls.ErrorDetails.LEVEL_LOAD_ERROR, Hls.ErrorDetails.LEVEL_LOAD_TIMEOUT].includes(data.details)) { advance(); return; } networkRetries += 1; if (networkRetries <= MAX_NETWORK_RETRIES) { retryTimer = setTimeout(() => { if (!cancelled && hlsRef.current === hls) hls.startLoad(-1); }, Math.min(1000 * networkRetries, 4000)); return; } } advance(); });
      hls.on(Hls.Events.MANIFEST_PARSED, () => { if (cancelled || hlsRef.current !== hls) return; const discovered = hls.levels.map((level, index) => ({ index, height: level.height, bitrate: level.bitrate })); setLevels(discovered); const networkCap = profile.capHeight === null ? -1 : Math.max(0, ...discovered.filter((level) => level.height <= profile.capHeight!).map((level) => level.index)); hls.autoLevelCapping = initialDataSaver ? Math.max(0, ...discovered.filter((level) => level.height <= DATA_SAVER_MAX_HEIGHT).map((level) => level.index)) : networkCap; hls.currentLevel = initialLevel !== undefined && initialLevel >= 0 ? initialLevel : 0; void el.play().catch(() => setAutoplayBlocked(true)); });
      hls.on(Hls.Events.LEVEL_SWITCHED, (_event, data) => { if (!cancelled) { setActiveLevel(data.level); setStats((current) => ({ ...current, bitrate: hls.levels[data.level]?.bitrate ?? null })); } });
      hls.on(Hls.Events.LEVEL_UPDATED, (_event, data) => { const edge = data.details.live ? data.details.edge : null; updateStats(edge === null ? null : Math.max(0, edge - el.currentTime)); }); hls.on(Hls.Events.FRAG_BUFFERED, () => { networkRetries = 0; updateStats(); });
    }
    const onPlaying = (): void => markReady(); const onCanPlay = (): void => { if (!Hls.isSupported()) markReady(); }; const onWaiting = (): void => { if (started) { rebufferCountRef.current += 1; setStats((current) => ({ ...current, rebufferCount: rebufferCountRef.current })); } setBuffering(true); }; const onPlayingReset = (): void => { if (started) { setBuffering(false); updateStats(); } }; const onError = (): void => advance();
    video.addEventListener('playing', onPlaying); video.addEventListener('canplay', onCanPlay); video.addEventListener('waiting', onWaiting); video.addEventListener('playing', onPlayingReset); video.addEventListener('error', onError); if (Hls.isSupported()) loadCurrent(); else if (video.canPlayType('application/vnd.apple.mpegurl')) { video.src = urls[urlIndex]; video.load(); } else setStatus('error');
    return () => { cancelled = true; retryRef.current = null; clearTimers(); destroy(); video.removeEventListener('playing', onPlaying); video.removeEventListener('canplay', onCanPlay); video.removeEventListener('waiting', onWaiting); video.removeEventListener('playing', onPlayingReset); video.removeEventListener('error', onError); };
  }, [urlsKey, initialDataSaver, initialLevel]);

  const activeHeight = levels.find((level) => level.index === activeLevel)?.height; const qualityLabel = selectedLevel === -1 ? `Auto${activeHeight ? ` · ${activeHeight}p` : ''}` : `${levels.find((level) => level.index === selectedLevel)?.height ?? 'Auto'}p`; const retry = (): void => { retryRef.current?.(); };
  useEffect(() => { const hls = hlsRef.current; if (!hls || levels.length === 0) return; hls.autoLevelCapping = dataSaver ? Math.max(0, ...levels.filter((level) => level.height <= DATA_SAVER_MAX_HEIGHT).map((level) => level.index)) : -1; hls.currentLevel = dataSaver ? -1 : selectedLevel; }, [dataSaver, selectedLevel, levels]);
  useEffect(() => { const video = videoRef.current; if (!video || initialVolume === undefined) return; video.volume = initialVolume; const onVolume = (): void => onVolumeChange?.(video.volume); video.addEventListener('volumechange', onVolume); return () => video.removeEventListener('volumechange', onVolume); }, [initialVolume, onVolumeChange]);
  const togglePlayback = (): void => { const video = videoRef.current; if (!video || status !== 'ready') return; if (video.paused) void video.play().catch(() => setAutoplayBlocked(true)); else video.pause(); };
  return <div className={styles.player} data-state={status}><video ref={videoRef} className={styles.video} controls playsInline onClick={togglePlayback} aria-label={`Lecteur ${title}`} />{status !== 'ready' && <div className={styles.overlay} role="status" aria-live="polite"><div className={styles.signal}><span className={styles.signalDot} /><span>{retrying ? 'Reconnexion au flux…' : status === 'error' ? 'Flux indisponible' : 'Connexion au direct'}</span></div>{status === 'loading' && <><Spinner /><p className={styles.hint}>Le lecteur démarre en qualité basse puis augmente selon le réseau.</p></>}{status === 'error' && <><h2 className={styles.title}>Lecture interrompue</h2><p className={styles.hint}>Le fournisseur ne répond pas ou la session a expiré.</p><button type="button" className={styles.retryButton} onClick={retry}>Réessayer</button></>}{status !== 'ready' && <div />}</div>}{status === 'ready' && buffering && <div className={styles.bufferingOverlay} role="status" aria-label="Mise en mémoire tampon"><Spinner /><span>Rattrapage du direct…</span></div>}{status === 'ready' && autoplayBlocked && <button type="button" className={styles.playPrompt} onClick={() => { const video = videoRef.current; if (video) void video.play().then(() => setAutoplayBlocked(false)).catch(() => undefined); }}>Lancer la lecture</button>}{status === 'ready' && <div className={styles.controlRail}><span className={styles.liveBadge}>DIRECT</span><span className={styles.stat}>Qualité {qualityLabel}</span><span className={styles.stat}>Buffer {formatBuffer(stats.bufferAhead)}</span><span className={styles.stat}>Démarrage {formatDuration(stats.startupMs)}</span>{stats.rebufferCount > 0 && <span className={styles.statWarning}>Rebuffers {stats.rebufferCount}</span>}<select className={styles.qualitySelect} value={dataSaver ? -1 : selectedLevel} aria-label="Qualité vidéo" onChange={(event) => { const level = Number(event.target.value); setSelectedLevel(level); onLevelChange?.(level); }}><option value={-1}>Auto</option>{levels.slice().sort((a, b) => b.height - a.height).map((level) => <option key={level.index} value={level.index}>{level.height}p</option>)}</select><label className={styles.dataSaverToggle}><input type="checkbox" checked={dataSaver} onChange={(event) => { const enabled = event.target.checked; setDataSaver(enabled); onDataSaverChange?.(enabled); }} />Éco</label></div>}</div>;
}
