import { Injectable, NotFoundException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { Channel, ChannelListResponse, ChannelQuery, CountryOption, NowPlaying, PlayResponse, Programme } from '@mbolo/contracts';
import { PrismaService } from '../../common/prisma/prisma.service';
import { StorageService } from '../../common/storage/storage.interface';
import { StreamingService } from '../streaming/streaming.service';

type ListedChannel = { id: string; name: string; canonicalName: string; country: string | null; categoryId: string | null; logoKey: string | null };
type CountryRow = { country: string | null; _count: { country: number } };
type ChannelProgramme = { id: string; channelId: string; startsAt: Date; endsAt: Date; title: string; description: string | null };

@Injectable()
export class ChannelsService {
  private readonly publicApiUrl: string; private readonly storageDriver: string; private readonly logoUrlTtlSeconds: number;
  constructor(private readonly prisma: PrismaService, private readonly streaming: StreamingService, private readonly storage: StorageService, config: ConfigService) { this.publicApiUrl = (config.get<string>('PUBLIC_API_URL') ?? config.get<string>('API_URL') ?? 'http://localhost:4000').replace(/\/+$/, ''); const configuredDriver = config.get<string>('STORAGE_DRIVER', 'local').trim().toLowerCase(); this.storageDriver = configuredDriver === 's3' || Boolean(config.get<string>('S3_ENDPOINT') && config.get<string>('S3_BUCKET')) ? 's3' : 'local'; this.logoUrlTtlSeconds = Math.min(Math.max(config.get<number>('S3_LOGO_URL_TTL_SECONDS', 300), 60), 3600); }
  async list(query: ChannelQuery): Promise<ChannelListResponse> {
    const where = { ...(query.category ? { category: { slug: query.category } } : {}), ...(query.country ? { country: query.country } : {}), ...(query.q ? { canonicalName: { contains: query.q } } : {}), variants: { some: { isActive: true, OR: [{ healthStatus: null }, { healthStatus: 'OK' }] } } };
    const [channels, total] = await Promise.all([this.prisma.channel.findMany({ where, orderBy: [{ sortOrder: 'asc' }, { canonicalName: 'asc' }], take: query.limit ?? 48, skip: query.offset ?? 0 }), this.prisma.channel.count({ where })]);
    const nowPlaying = await this.findNowPlaying(channels.map((channel: { id: string }) => channel.id)); const healthByChannel = await this.findHealthStatus(channels.map((channel: { id: string }) => channel.id)); const items = await Promise.all(channels.map((channel: ListedChannel) => this.serialize(channel, nowPlaying.get(channel.id) ?? null, healthByChannel.get(channel.id) ?? null)));
    return { items, total, hasMore: (query.offset ?? 0) + items.length < total };
  }
  async countries(): Promise<CountryOption[]> { const rows = await this.prisma.channel.groupBy({ by: ['country'], where: { country: { not: null }, variants: { some: { isActive: true, OR: [{ healthStatus: null }, { healthStatus: 'OK' }] } } }, _count: { country: true } }); return rows.filter((row: CountryRow) => row.country !== null).map((row: CountryRow) => ({ slug: row.country as string, name: row.country as string, count: row._count.country })).sort((a: CountryOption, b: CountryOption) => b.count - a.count); }
  async findOne(id: string): Promise<Channel> { const channel = await this.prisma.channel.findFirst({ where: { id, variants: { some: { isActive: true, OR: [{ healthStatus: null }, { healthStatus: 'OK' }] } } } }); if (!channel) throw new NotFoundException('Channel not found'); return this.serialize(channel, (await this.findNowPlaying([id])).get(id) ?? null, (await this.findHealthStatus([id])).get(id) ?? null); }
  async epg(id: string): Promise<Programme[]> { const channel = await this.prisma.channel.findUnique({ where: { id } }); if (!channel) throw new NotFoundException('Channel not found'); const from = new Date(Date.now() - 3 * 3_600_000); const to = new Date(Date.now() + 12 * 3_600_000); const programmes = await this.prisma.epgProgramme.findMany({ where: { channelId: id, startsAt: { lte: to }, endsAt: { gte: from } }, orderBy: { startsAt: 'asc' } }); return programmes.map((programme: ChannelProgramme) => ({ id: programme.id, channelId: programme.channelId, startsAt: programme.startsAt.toISOString(), endsAt: programme.endsAt.toISOString(), title: programme.title, description: programme.description })); }
  async play(id: string): Promise<PlayResponse> { if (!(await this.prisma.channel.findUnique({ where: { id } }))) throw new NotFoundException('Channel not found'); return this.streaming.createPlay(id); }
  private async findNowPlaying(channelIds: string[]): Promise<Map<string, NowPlaying>> { if (channelIds.length === 0) return new Map(); const programmes = await this.prisma.epgProgramme.findMany({ where: { channelId: { in: channelIds }, startsAt: { lte: new Date() }, endsAt: { gt: new Date() } } }); const map = new Map<string, NowPlaying>(); for (const programme of programmes) if (!map.has(programme.channelId)) map.set(programme.channelId, { startsAt: programme.startsAt.toISOString(), endsAt: programme.endsAt.toISOString(), title: programme.title }); return map; }
  private async findHealthStatus(channelIds: string[]): Promise<Map<string, 'OK' | 'DOWN'>> { if (channelIds.length === 0) return new Map(); const variants = await this.prisma.streamVariant.findMany({ where: { channelId: { in: channelIds }, isActive: true }, select: { channelId: true, healthStatus: true } }); const map = new Map<string, 'OK' | 'DOWN'>(); for (const variant of variants) if (variant.healthStatus !== null && (map.get(variant.channelId) === undefined || variant.healthStatus === 'OK')) map.set(variant.channelId, variant.healthStatus as 'OK' | 'DOWN'); return map; }
  private async serialize(channel: ListedChannel, nowPlaying: NowPlaying | null, healthStatus: 'OK' | 'DOWN' | null): Promise<Channel> { return { id: channel.id, name: channel.name, canonicalName: channel.canonicalName, country: channel.country, categoryId: channel.categoryId, logoUrl: await this.resolveLogoUrl(channel.logoKey), healthStatus, nowPlaying }; }
  private async resolveLogoUrl(logoKey: string | null): Promise<string | null> { if (!logoKey || /^https?:\/\//i.test(logoKey)) return null; try { return this.storageDriver === 's3' ? await this.storage.signedUrl(logoKey, this.logoUrlTtlSeconds) : `${this.publicApiUrl}/uploads/${logoKey}`; } catch { return null; } }
}
